stages:
  prepare:
    cmd: poetry run python -m src.prepare_data
    deps:
      - data/raw/creditcard.csv
      - src/prepare_data.py
      - src/features.py
      - src/config.py
    outs:
      - artifacts/X_train.joblib
      - artifacts/X_test.joblib
      - artifacts/y_train.joblib
      - artifacts/y_test.joblib

  train:
    cmd: poetry run python -m src.train_model
    deps:
      - artifacts/X_train.joblib
      - artifacts/y_train.joblib
      - src/train_model.py
      - src/config.py
    params:
      - train
    outs:
      - artifacts/model_xgb.joblib

  evaluate:
    cmd: poetry run python -m src.evaluate
    deps:
      - artifacts/X_test.joblib
      - artifacts/y_test.joblib
      - artifacts/model_xgb.joblib
      - src/evaluate.py
      - src/config.py
    params:
      - eval
    metrics:
      - artifacts/metrics.json
    outs:
      - artifacts/graphs.png
      - artifacts/metrics_prev.json
